import React from "react";
import CommonButton from "@/components/CommonButton";
import TextCard from "@/components/TextCard";
import type { InsuredBeneficiaryPairData } from "@/types";
import {
  formatFullName,
  formatFullNameKana,
  formatAddress,
  formatPostalCode,
  formatPhoneNumber,
  formatBirthDate,
} from "@/utils/formatUtils";
import styles from "@/components/FormCard.module.css";
import FormCard from "../FormCard";
import PremiumDisplay from "../PremiumDisplay";

// TODO: better UI/UX
const INSURANCE_FEE_INFO =
  "※保険年齢が上がった場合、それに伴い保険料が変更される場合がありますので、あらかじめご了承ください";

interface InsuredBeneficiaryPairViewModalProps {
  onClose: () => void;
  data: InsuredBeneficiaryPairData;
  mode?: "view" | "confirmation"; // NEW
  onConfirm?: () => void; // NEW - for confirmation mode
  onEdit?: () => void; // NEW - go back to edit
}

const InsuredBeneficiaryPairViewModal: React.FC<
  InsuredBeneficiaryPairViewModalProps
> = ({ onClose, data, mode, onConfirm, onEdit }) => {
  return (
    <div className={styles.mainFormCard}>
      <div className={styles.formCardHeader}>
        <h2>登録内容確認</h2>
      </div>

      <div className={styles.formFields}>
        {/* 被保険者情報 */}
        <TextCard title="被保険者">
          <div className={styles.formFields}>
            <div className={styles.formField}>
              <span className={styles.fieldLabel}>氏名</span>
              <span className={styles.fieldValue}>
                {formatFullName(data.insured.lastName, data.insured.firstName)}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>フリガナ</span>
              <span className={styles.fieldValue}>
                {formatFullNameKana(
                  data.insured.lastNameKana,
                  data.insured.firstNameKana
                )}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>生年月日</span>
              <span className={styles.fieldValue}>
                {formatBirthDate(data.insured.birthDate)}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>性別</span>
              <span className={styles.fieldValue}>{data.insured.gender}</span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>
                続柄（被保険者から見た契約者の続柄）
              </span>
              <span className={styles.fieldValue}>
                {data.insured.relationship}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>郵便番号</span>
              <span className={styles.fieldValue}>
                {formatPostalCode(data.insured.postalCode)}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>住所</span>
              <span className={styles.fieldValue}>
                {formatAddress(
                  data.insured.prefecture,
                  data.insured.city,
                  data.insured.address,
                  data.insured.building
                )}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>電話番号</span>
              <span className={styles.fieldValue}>
                {formatPhoneNumber(data.insured.phoneNumber)}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>メールアドレス</span>
              <span className={styles.fieldValue}>{data.insured.email}</span>
            </div>
          </div>
        </TextCard>

        {/* // TODO: fix CSS here
        //  保険料・登録情報 */}

        {/*   <TextCard title="保険料">
          <div className={styles.formField}>
            <span className={styles.fieldLabel}>保険料（月払い）</span>
            <span className={styles.fieldValue}>590円</span>
          </div> */}

        {/*  <div className={styles.formField}>
              <span className={styles.fieldLabel}>保険料注意事項</span>
            </div> */}
        {/* </TextCard> */}
        <PremiumDisplay
          birthday={data.insured.birthDate}
          gender={data.insured.gender === "男性" ? "male" : "female"}
        />

        {/*   <div>
          <p>{INSURANCE_FEE_INFO}</p> */}
        {/* generated by figma to code (tailwind/JSX) */}
        
        <p className="flex text-black text-base font-normal font-['Inter']">
          <span className="w-4 flex-shrink-0">※</span>
          <span>
            保険年齢が上がった場合、それに伴い保険料が変更される場合がありますので、あらかじめご了承ください
          </span>
        </p>
          

        {/*   </div> */}
        {/* 受取人情報 */}
        <TextCard title="死亡保険金受取人">
          <div className={styles.formFields}>
            <div className={styles.formField}>
              <span className={styles.fieldLabel}>氏名</span>
              <span className={styles.fieldValue}>
                {formatFullName(
                  data.beneficiary.lastName,
                  data.beneficiary.firstName
                )}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>フリガナ</span>
              <span className={styles.fieldValue}>
                {formatFullNameKana(
                  data.beneficiary.lastNameKana,
                  data.beneficiary.firstNameKana
                )}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>生年月日</span>
              <span className={styles.fieldValue}>
                {formatBirthDate(data.beneficiary.birthDate)}
              </span>
            </div>

            {/* <div className={styles.formField}>
              <span className={styles.fieldLabel}>性別</span>
              <span className={styles.fieldValue}>
                {data.beneficiary.gender}
              </span>
            </div> */}

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>
                続柄（被保険者から見た死亡保険金受取人の続柄）
              </span>
              <span className={styles.fieldValue}>
                {data.beneficiary.relationship}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>郵便番号</span>
              <span className={styles.fieldValue}>
                {formatPostalCode(data.beneficiary.postalCode)}
              </span>
            </div>

            <div className={styles.formField}>
              <span className={styles.fieldLabel}>住所</span>
              <span className={styles.fieldValue}>
                {formatAddress(
                  data.beneficiary.prefecture,
                  data.beneficiary.city,
                  data.beneficiary.address,
                  data.beneficiary.building
                )}
              </span>
            </div>

            {/*  <div className={styles.formField}>
              <span className={styles.fieldLabel}>電話番号</span>
              <span className={styles.fieldValue}>
                {formatPhoneNumber(data.beneficiary.phoneNumber)}
              </span>
            </div> */}

            {/* <div className={styles.formField}>
              <span className={styles.fieldLabel}>メールアドレス</span>
              <span className={styles.fieldValue}>
                {data.beneficiary.email}
              </span>
            </div> */}
          </div>
        </TextCard>
      </div>
      {/* Action buttons */}

      {mode === "confirmation" && (
        <div
          className={styles.stepActionButtons}
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <CommonButton variant="primary" onClick={onConfirm}>
            {data.status === "temp" ? "登録する" : "更新する"}
            {/* // TODO: fix here, very ugly*/}
          </CommonButton>
          <CommonButton variant="outline" onClick={onEdit}>
            戻る
          </CommonButton>
        </div>
      )}
      {/* // TODO: write a better CSS here */}
      {mode === "view" && (
        <div
          className={styles.stepActionButtons}
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <CommonButton variant="outline" onClick={onClose}>
            戻る
          </CommonButton>
        </div>
      )}
    </div>
  );
};

export default InsuredBeneficiaryPairViewModal;
